apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cloudlords
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
        owner: CloudKnightOps
        repo: Pull-request-test
        labels:
        - preview
      requeueAfterSeconds: 90
  template:
    metadata:
      name: 'cloudraiders-{{branch}}-{{number}}'
      namespace: cloudlords-mount
    spec:
      source:
        repoURL: 'https://github.com/CloudknightOps/Pull-request-test.git'
        targetRevision: '{{head_sha}}'
        path: deploy
      project: "default"
      destination:
        server: https://kubernetes.default.svc
        namespace: cloudlords-{{branch}}-{{number}}
      syncPolicy:
         syncOptions:
          - CreateNamespace=true