apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudknight
  labels:
    app: cloudknight
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudknight
  template:
    metadata:
      labels:
        app: cloudknight
    spec:
      containers:
        - name: cloudknight
          image: cloudopsknight/cloudraiders:483ddf339cbf9f24b5d29e6fd0b6a00d57055a5b
          ports:
            - containerPort: 8080
