name: Github CICD pipeline job
on:
  push:
    branches: [ "main" ]


jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "building and testing the app ..."
  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.5.0
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push to Dockerhub 
        uses: docker/build-push-action@v2
        with:
          context: .
          file: src/Dockerfile
          push: true
          tags: cloudopsknight/cloudknight:latest, cloudopsknight/cloudknight:${{ github.sha }}
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_TOKEN }}
  update-deployment:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
    - name: Get Image Tag
      id: tag
      run: echo ::set-output name=tag::${{ github.sha }}
      
    - name: Checkout code
      uses: actions/checkout@v3
      
      
    - name: Set file permissions
      run: chmod 777 deploy/deployment.yml

    - name: Update Deployment YAML
      run: |
        sed -i "s/image:.*$/image: cloudopsknight\/cloudknight:${{ steps.tag.outputs.tag }}/g" deploy/deployment.yml
        cat deploy/deployment.yml
      env:
        github_token: ${{ secrets.GH_PAT }}
        
    - name: Commit changes
      run: |
        git config --global user.email "ci-bot@argocd.com"
        git config --global user.name "ci-bot"
        git add deploy/deployment.yml    
        git commit -m "Update image tag [skip ci]"
      env:
        github_token: ${{ secrets.GH_PAT}}
        
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_PAT}}
        branch: ${{ github.ref }}

      